{% set name = "xbout" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51b6bcc888553037a623f68dccfe7755ca409801d5b2dd1b8b1ecaca78c1eff1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.0
    - pip
    - setuptools
  run:
    - python >=3.8.0
    - xarray >=0.18.0,<2022.9.0
    - boutdata >=0.1.4
    - dask >=2.10.0
    - gelidum >=0.5.3
    - natsort >=5.5.0
    - matplotlib-base >=3.1.1,!=3.3.0,!=3.3.1,!=3.3.2
    - animatplot >=0.4.2
    - netcdf4 >=1.4.0
    - Pillow >=6.1.0

test:
  requires:
    - pytest >=3.3.0
  commands:
    - pytest --pyargs xbout

about:
  home: https://xbout.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Collect data from BOUT++ runs in python using xarray
  dev_url: https://github.com/boutproject/xBOUT

extra:
  recipe-maintainers:
    - johnomotani
    - ZedThree
