{% set name = "xbout" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a62b6f53ad35c3f2d99988b2f8236781773608e505646765255e8b8080d1db9

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6.0
    - pip
  run:
    - python >=3.6.0
    - xarray >=0.17.0
    - boutdata >=0.1.4
    - dask >=2.10.0
    - natsort >=5.5.0
    - matplotlib-base >=3.1.1
    - animatplot >=0.4.2
    - netcdf4 >=1.4.0
    - Pillow >=6.1.0
    - importlib-metadata

test:
  requires:
    - pytest >=3.3.0
  commands:
    - pip install xarray==0.17.2 # temporarily downgrade xarray to avoid bug that will be fixed in xbout-0.2.5
    - pytest --pyargs xbout

about:
  home: https://xbout.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Collect data from BOUT++ runs in python using xarray
  dev_url: https://github.com/boutproject/xBOUT

extra:
  recipe-maintainers:
    - johnomotani
    - ZedThree
