{% set name = "xbout" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 246fd6d858aa41a4f0b51f8c97d7a20c9b537f21ddb12f670b745e10b2d03ac7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.0
    - pip
  run:
    - python >=3.7.0
    - xarray >=0.18.0
    - boutdata >=0.1.4
    - dask >=2.10.0
    - natsort >=5.5.0
    - matplotlib-base >=3.1.1
    - animatplot >=0.4.2
    - netcdf4 >=1.4.0
    - Pillow >=6.1.0
    - importlib-metadata

test:
  requires:
    - pytest >=3.3.0
  commands:
    - pytest --pyargs xbout

about:
  home: https://xbout.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Collect data from BOUT++ runs in python using xarray
  dev_url: https://github.com/boutproject/xBOUT

extra:
  recipe-maintainers:
    - johnomotani
    - ZedThree
